### PR TITLE
fix link problem on MacOS

### LINKED ISSUE #383: Compilation Issue on MacOS
I have problems compiling the OMP version on MacOS:
>>>
[ 16%] Linking CXX shared library libginkgo_omp.dylib
Undefined symbols for architecture x86_64:
  "gko::OmpExecutor::raw_copy_to(gko::HipExecutor const*, unsigned long, void const*, void*) const", referenced from:
      vtable for gko::OmpExecutor in executor.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [omp/libginkgo_omp.dylib] Error 1
make[1]: *** [omp/CMakeFiles/ginkgo_omp.dir/all] Error 2
<<<

the complete CMake cache attached.
[CMakeCache.txt](https://github.com/ginkgo-project/ginkgo/files/3848777/CMakeCache.txt)

[CMakeOutput.log](https://github.com/ginkgo-project/ginkgo/files/3848786/CMakeOutput.log)
[CMakeError.log](https://github.com/ginkgo-project/ginkgo/files/3848787/CMakeError.log)

### PR DESCRIPTION
**Pull request by yhmtsai**
This PR fix missing link which leads the `undefined symbols` on MacOS.

@tcojean Does reference module also need to link ginkgo_hip/ginkgo_cuda like ginkgo_omp
@hartwiganzt Could you test it with `-DGINKGO_BUILD_OMP=ON` and `-DGINKGO_BUILD_OMP=OFF`

Closes #383

### CODE REVIEW

**Comment by nbeams** [comment]
@hartwiganzt asked me to test this since it was prompted by a failed build attempt on my Mac. 

I can confirm successful builds on MacOS 10.14.6, with both `-DGINKGO_BUILD_OMP=ON` and `-DGINKGO_BUILD_OMP=OFF`.  I built with GCC 8.3.0.  Thanks!

**Comment by yhmtsai** [comment]
This PR fixes the missing link which leads that undefined symbols `OmpExecutor::raw_copy_to(gko::HipExecutor ...`

Related PR: https://github.com/ginkgo-project/ginkgo/pull/384
